import {
  FDI_BABY_TEETH,
  FDI_BABY_TEETH_LOWER,
  FDI_BABY_TEETH_LOWER_LEFT,
  FDI_BABY_TEETH_LOWER_RIGHT,
  FDI_BABY_TEETH_UPPER,
  FDI_BABY_TEETH_UPPER_LEFT,
  FDI_BABY_TEETH_UPPER_RIGHT,
  FDI_PRIMARY_TEETH,
  FDI_PRIMARY_TEETH_LOWER,
  FDI_PRIMARY_TEETH_LOWER_LEFT,
  FDI_PRIMARY_TEETH_LOWER_RIGHT,
  FDI_PRIMARY_TEETH_UPPER,
  FDI_PRIMARY_TEETH_UPPER_LEFT,
  FDI_PRIMARY_TEETH_UPPER_RIGHT,
  FDI_TEETH,
  FdiBabyTeeth,
  FdiBabyTeethLower,
  FdiBabyTeethLowerLeft,
  FdiBabyTeethLowerRight,
  FdiBabyTeethUpper,
  FdiBabyTeethUpperLeft,
  FdiBabyTeethUpperRight,
  FdiPrimaryTeeth,
  FdiPrimaryTeethLower,
  FdiPrimaryTeethLowerLeft,
  FdiPrimaryTeethLowerRight,
  FdiPrimaryTeethUpper,
  FdiPrimaryTeethUpperLeft,
  FdiPrimaryTeethUpperRight,
  FdiTeeth
} from "./fdi";
import { PalmerTeeth } from "./palmer";
import {
  UNIVERSAL_BABY_TEETH,
  UNIVERSAL_BABY_TEETH_LOWER,
  UNIVERSAL_BABY_TEETH_LOWER_LEFT,
  UNIVERSAL_BABY_TEETH_LOWER_RIGHT,
  UNIVERSAL_BABY_TEETH_UPPER,
  UNIVERSAL_BABY_TEETH_UPPER_LEFT,
  UNIVERSAL_BABY_TEETH_UPPER_RIGHT,
  UNIVERSAL_PRIMARY_TEETH,
  UNIVERSAL_PRIMARY_TEETH_LOWER,
  UNIVERSAL_PRIMARY_TEETH_LOWER_LEFT,
  UNIVERSAL_PRIMARY_TEETH_LOWER_RIGHT,
  UNIVERSAL_PRIMARY_TEETH_UPPER,
  UNIVERSAL_PRIMARY_TEETH_UPPER_LEFT,
  UNIVERSAL_PRIMARY_TEETH_UPPER_RIGHT,
  UNIVERSAL_TEETH,
  UniversalBabyTeeth,
  UniversalBabyTeethLower,
  UniversalBabyTeethLowerLeft,
  UniversalBabyTeethLowerRight,
  UniversalBabyTeethUpper,
  UniversalBabyTeethUpperLeft,
  UniversalBabyTeethUpperRight,
  UniversalPrimaryTeeth,
  UniversalPrimaryTeethLower,
  UniversalPrimaryTeethLowerLeft,
  UniversalPrimaryTeethLowerRight,
  UniversalPrimaryTeethUpper,
  UniversalPrimaryTeethUpperLeft,
  UniversalPrimaryTeethUpperRight,
  UniversalTeeth
} from "./universal";
import { convertTeeth, getTeethString } from "./utils";

type Teeth = FdiTeeth | UniversalTeeth | PalmerTeeth;

type NotationType = "fdi" | "universal" | "palmer";

export {
  FDI_BABY_TEETH,
  FDI_BABY_TEETH_LOWER,
  FDI_BABY_TEETH_LOWER_LEFT,
  FDI_BABY_TEETH_LOWER_RIGHT,
  FDI_BABY_TEETH_UPPER,
  FDI_BABY_TEETH_UPPER_LEFT,
  FDI_BABY_TEETH_UPPER_RIGHT,
  FDI_PRIMARY_TEETH,
  FDI_PRIMARY_TEETH_LOWER,
  FDI_PRIMARY_TEETH_LOWER_LEFT,
  FDI_PRIMARY_TEETH_LOWER_RIGHT,
  FDI_PRIMARY_TEETH_UPPER,
  FDI_PRIMARY_TEETH_UPPER_LEFT,
  FDI_PRIMARY_TEETH_UPPER_RIGHT,
  FDI_TEETH,
  UNIVERSAL_BABY_TEETH,
  UNIVERSAL_BABY_TEETH_LOWER,
  UNIVERSAL_BABY_TEETH_LOWER_LEFT,
  UNIVERSAL_BABY_TEETH_LOWER_RIGHT,
  UNIVERSAL_BABY_TEETH_UPPER,
  UNIVERSAL_BABY_TEETH_UPPER_LEFT,
  UNIVERSAL_BABY_TEETH_UPPER_RIGHT,
  UNIVERSAL_PRIMARY_TEETH,
  UNIVERSAL_PRIMARY_TEETH_LOWER,
  UNIVERSAL_PRIMARY_TEETH_LOWER_LEFT,
  UNIVERSAL_PRIMARY_TEETH_LOWER_RIGHT,
  UNIVERSAL_PRIMARY_TEETH_UPPER,
  UNIVERSAL_PRIMARY_TEETH_UPPER_LEFT,
  UNIVERSAL_PRIMARY_TEETH_UPPER_RIGHT,
  UNIVERSAL_TEETH,
  convertTeeth,
  getTeethString
};

export type {
  FdiBabyTeeth,
  FdiBabyTeethLower,
  FdiBabyTeethLowerLeft,
  FdiBabyTeethLowerRight,
  FdiBabyTeethUpper,
  FdiBabyTeethUpperLeft,
  FdiBabyTeethUpperRight,
  FdiPrimaryTeeth,
  FdiPrimaryTeethLower,
  FdiPrimaryTeethLowerLeft,
  FdiPrimaryTeethLowerRight,
  FdiPrimaryTeethUpper,
  FdiPrimaryTeethUpperLeft,
  FdiPrimaryTeethUpperRight,
  FdiTeeth,
  NotationType,
  PalmerTeeth,
  Teeth,
  UniversalBabyTeeth,
  UniversalBabyTeethLower,
  UniversalBabyTeethLowerLeft,
  UniversalBabyTeethLowerRight,
  UniversalBabyTeethUpper,
  UniversalBabyTeethUpperLeft,
  UniversalBabyTeethUpperRight,
  UniversalPrimaryTeeth,
  UniversalPrimaryTeethLower,
  UniversalPrimaryTeethLowerLeft,
  UniversalPrimaryTeethLowerRight,
  UniversalPrimaryTeethUpper,
  UniversalPrimaryTeethUpperLeft,
  UniversalPrimaryTeethUpperRight,
  UniversalTeeth
};
